name: Python Commit

on:
  push:

jobs:
  python:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le repository
        uses: actions/checkout@v4

      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Lancer le script
        run: python scripts/commit.py